name: Deploy to Cloud Run

on:
  push:
    branches:
      - producao   # dispara quando há push na branch "producao"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Configura Java 21 (Temurin)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3) Compila o projeto (caso queira rodar testes: retire o -DskipTests)
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 4) Autentica com o Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5) Configura o gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'  # Opcional: instala componentes beta se necessário

      # 6) Build da imagem e push para Container Registry (gcr.io) usando Cloud Build
      - name: Build and push image
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-spring"
          gcloud builds submit --pack image="$IMAGE" .

      # 7) Deploy no Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-spring"
          # Deploy, setando as variáveis de ambiente necessárias
          gcloud run deploy todo-spring \
            --image "$IMAGE" \
            --region "southamerica-east1" \
            --platform "managed" \
            --allow-unauthenticated \
            --set-env-vars DB_USERNAME=sqlserver,DB_PASSWORD=123456,DB_URL="jdbc:sqlserver://34.95.138.204:1433;databaseName=todo_db",SERVER_PORT=8080
