nome: Deploy Elastic Beanstalk

on:
  push:
    branches:
      - producao

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'todo-desafio-spring'
          environment_name: 'todo-desafio-spring-prod'
          version_label: ${{ github.sha }}
          region: us-east-2
          deployment_package: target/todo-0.0.1-SNAPSHOT.jar
