name: Deploy to Cloud Run

on:
  push:
    branches:
      - producao   # dispara quando h치 push na branch "producao"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout do reposit칩rio
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Configura Java 21 (Temurin)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3) Compila o projeto (caso queira rodar testes: retire o -DskipTests)
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 4) Instala e configura gcloud CLI usando service account
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 5) Build da imagem e push para Container Registry (gcr.io)
      - name: Build and push image
        run: |
          # Nome da imagem (mude "todo-spring" se quiser)
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-spring"
          # Faz build usando Cloud Build e envia para o Container Registry
          gcloud builds submit --pack image="$IMAGE" .

      # 6) Deploy no Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-spring"
          # Deploy, setando as vari치veis de ambiente necess치rias
          gcloud run deploy todo-spring \
            --image "$IMAGE" \
            --region "southamerica-east1" \
            --platform "managed" \
            --allow-unauthenticated \
            --set-env-vars DB_USERNAME=sqlserver,DB_PASSWORD=123456,DB_URL="jdbc:sqlserver://34.95.138.204:1433;databaseName=todo_db",SERVER_PORT=8080
